CREATE DATABASE Baitap3;
USE Baitap3;

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE VARCHAR(11) NOT NULL UNIQUE,
    DATEOFBIRTH DATE NOT NULL,
    STATUS BIT,
    BALANCE DOUBLE DEFAULT 0.0
);

CREATE TABLE TRANSFER (
    SENDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    RECEIVER_ID INT,
    MONEY DOUBLE,
    TRANSFER_DATE DATE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(ID)
);

DELIMITER //
CREATE PROCEDURE TransferMoney(IN sender_id INT, IN receiver_id INT, IN amount DOUBLE)
BEGIN
    DECLARE sender_balance DOUBLE;
    START TRANSACTION;
    SELECT BALANCE INTO sender_balance FROM USERS WHERE ID = sender_id;
    IF sender_balance >= amount THEN
        UPDATE USERS SET BALANCE = BALANCE - amount WHERE ID = sender_id;
        UPDATE USERS SET BALANCE = BALANCE + amount WHERE ID = receiver_id;
        INSERT INTO TRANSFER (SENDER_ID, RECEIVER_ID, MONEY, TRANSFER_DATE)
        VALUES (sender_id, receiver_id, amount, CURDATE());
        COMMIT;
    ELSE
        ROLLBACK;
    END IF;
END //

DELIMITER ;TransferMoney

