CREATE DATABASE BAITAP3;
USE BAITAP3;

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE VARCHAR(11) NOT NULL UNIQUE,
    DATEOFBIRTH DATE NOT NULL,
    STATUS BIT
);

CREATE TABLE TRANSFER (
    SENDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    RECEIVER_ID INT,
    MONEY DOUBLE,
    TRANSFER_DATE DATE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(ID)
);

START TRANSACTION;
SET @SENDER_ID = 1;
SET @RECEIVER_ID = 2;
SET @AMOUNT = 100.00;
SELECT (SELECT BALANCE FROM USERS WHERE ID = @SENDER_ID) INTO @SENDER_BALANCE;
IF @SENDER_BALANCE >= @AMOUNT THEN
    UPDATE USERS SET BALANCE = BALANCE - @AMOUNT WHERE ID = @SENDER_ID;
    UPDATE USERS SET BALANCE = BALANCE + @AMOUNT WHERE ID = @RECEIVER_ID;
    INSERT INTO TRANSFER (SENDER_ID, RECEIVER_ID, MONEY, TRANSFER_DATE)
    VALUES (@SENDER_ID, @RECEIVER_ID, @AMOUNT, CURDATE());
    COMMIT;
ELSE
    ROLLBACK;
END IF;
